# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc9bec69407469c1307c87fe3e0182fab0135fd0996ecc9129f8afe5c40302003515bc6b94272b54e6fbaf98dc14549841d7dc504b7a171dd84d53a3a28e5146

test:
  secret_key_base: 990b15d236744869287b991f780d44144024609aed28f780478ad13d006501e5cd7966a4c503278ec9aab47fe2baad4e64d65982c5db48a4d0701ffc3ccb3444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
